const PERCENT = x => Math.round(x * 100000, 6) / 1000;

const WHITELIST = "αΑβΒχΧδΔεΕηΗγΓιΙκΚλΛμΜνΝωΩοΟφΦπΠψΨρΡσΣτΤθΘυΥξΞζΖ";

const CHAR_TO_NAME = {
    'Α': 'Alpha',
    'α': 'Alpha',
    'Β': 'Beta',
    'β': 'Beta',
    'Χ': 'Chi',
    'χ': 'Chi',
    'Δ': 'Delta',
    'δ': 'Delta',
    'Ε': 'Epsilon',
    'ε': 'Epsilon',
    'Η': 'Eta',
    'η': 'Eta',
    'γ': 'Gamma',
    'Γ': 'Gamma',
    'ι': 'Iota',
    'Ι': 'Iota',
    'κ': 'Kappa',
    'Κ': 'Kappa',
    'λ': 'Lambda',
    'Λ': 'Lambda',
    'μ': 'Mu',
    'Μ': 'Mu',
    'ν': 'Nu',
    'Ν': 'Nu',
    'ω': 'Omega',
    'Ω': 'Omega',
    'ο': 'Omicron',
    'Ο': 'Omicron',
    'φ': 'Phi',
    'Φ': 'Phi',
    'π': 'Pi',
    'Π': 'Pi',
    'ψ': 'Psi',
    'Ψ': 'Psi',
    'ρ': 'Rho',
    'Ρ': 'Rho',
    'σ': 'Sigma',
    'Σ': 'Sigma',
    'Τ': 'Tau',
    'τ': 'Tau',
    'Θ': 'Theta',
    'θ': 'Theta',
    'υ': 'Upsilon',
    'Υ': 'Upsilon',
    'Ξ': 'Xi',
    'ξ': 'Xi',
    'Ζ': 'Zeta',
    'ζ': 'Zeta'
};

const CHAR_TO_NUM = {
    'Alpha': 0,
    'Beta': 1,
    'Chi': 2,
    'Delta': 3,
    'Epsilon': 4,
    'Eta': 5,
    'Gamma': 6,
    'Iota': 7,
    'Kappa': 8,
    'Lambda': 9,
    'Mu': 10,
    'Nu': 11,
    'Omega': 12,
    'Omicron': 13,
    'Phi': 14,
    'Pi': 15,
    'Psi': 16,
    'Rho': 17,
    'Sigma': 18,
    'Tau': 19,
    'Theta': 20,
    'Upsilon': 21,
    'Xi': 22,
    'Zeta': 23
};

const CHAR_CLASS = [
    "Alpha",
    "Beta",
    "Chi",
    "Delta",
    "Epsilon",
    "Eta",
    "Gamma",
    "Iota",
    "Kappa",
    "Lambda",
    "Mu" ,
    "Nu" ,
    "Omega" ,
    "Omicron" ,
    "Phi" ,
    "Pi" ,
    "Psi" ,
    "Rho" ,
    "Sigma" , 
    "Tau" ,
    "Theta" ,
    "Upsilon" ,
    "Xi",
    "Zeta",
];

const ROW_HEADER = [...CHAR_CLASS, "Best"]

const MODEL_DIRS = ["cnn", "resnet", "tesseract"];